networks:
  oscarmysql:
    external: true

services:
  app:
    build:
      context: .
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app:delegated
    networks:
      default:
        aliases:
          - oscar.db.dockers
      oscarmysql:
        aliases:
          - oscar.db.dockers
    restart: unless-stopped
